#mybatis配置
mybatis:
    type-aliases-package: com.wp.spring.study.common.db.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.wp.spring.study.common.db.base.ReadMapper
        - com.wp.spring.study.common.db.base.WriteMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql